apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo
  namespace: argocd

spec:
  project: my-argocd-project

  source:
    repoURL: https://github.com/sergi-learns-devops/argocd-demo.git
    targetRevision: HEAD
    path: files
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-demo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
